-- OFMS Supabase schema
-- This matches the database fields used by the provided Python database.py.
-- Run this in Supabase SQL Editor before using the HTML clone.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null,
  password_hash text not null,
  created_at text not null,
  display_name text,
  role text,
  office text,
  last_login text
);

create unique index if not exists idx_users_username_nocase
on public.users (lower(username));

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  title text not null,
  excel_path text not null,
  uploaded_by text not null,
  uploaded_at text not null,
  modified_at text not null,
  status text not null default 'Active',
  total_responses integer default 0,
  date_from text,
  date_to text,
  remaining_cards integer default 0,
  backlogs integer default 0,
  summary_json text not null,
  pdf_path text,
  deleted_at text
);

create table if not exists public.system_logs (
  id bigint generated by default as identity primary key,
  username text not null,
  action text not null,
  target_type text not null,
  target_id text,
  details text,
  logged_at text not null
);

-- Development/demo policies for the browser HTML clone.
-- For production, replace these with stricter authenticated-user policies.
alter table public.users enable row level security;
alter table public.reports enable row level security;
alter table public.system_logs enable row level security;

drop policy if exists "OFMS browser users read" on public.users;
drop policy if exists "OFMS browser users insert" on public.users;
drop policy if exists "OFMS browser users update" on public.users;
drop policy if exists "OFMS browser reports read" on public.reports;
drop policy if exists "OFMS browser reports insert" on public.reports;
drop policy if exists "OFMS browser reports update" on public.reports;
drop policy if exists "OFMS browser logs read" on public.system_logs;
drop policy if exists "OFMS browser logs insert" on public.system_logs;

create policy "OFMS browser users read" on public.users for select using (true);
create policy "OFMS browser users insert" on public.users for insert with check (true);
create policy "OFMS browser users update" on public.users for update using (true) with check (true);

create policy "OFMS browser reports read" on public.reports for select using (true);
create policy "OFMS browser reports insert" on public.reports for insert with check (true);
create policy "OFMS browser reports update" on public.reports for update using (true) with check (true);

create policy "OFMS browser logs read" on public.system_logs for select using (true);
create policy "OFMS browser logs insert" on public.system_logs for insert with check (true);


-- Compatibility upgrade for existing Supabase projects.
alter table public.users add column if not exists role text default 'Administrator';
alter table public.users add column if not exists office text default 'Office of the Adjutant';
